### PR TITLE
Fixes #41: Don’t panic on invalid comparisons.

### LINKED ISSUE #41: v0.7.0: Expression `size == "50"` causes a panic.
I would expect that no expression can panic the interpreter. 

```
unable to compare String("50") with Function("size", None)
thread 'limit::tests::cel::size_function_and_size_var' panicked at /Users/chirino/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cel-interpreter-0.7.0/src/objects.rs:270:23:
unable to compare String("50") with Function("size", None)
```

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
This should fix #41

**Comment by clarkmcc** [comment]
The PartialEq implementation looks good, but I'm thinking that we actually want to return a None on the PartialOrd implementation. I need to check the spec again and see.

As a note, there are currently a few other places where we have panics, which you can see by searching for unreachable!.

Agreed that nothing should panic.

File: interpreter/src/objects.rs [hunk 1]
```diff
@@ -304,7 +305,11 @@ impl PartialOrd for Value {
             (Value::UInt(a), Value::Float(b)) => (*a as f64).partial_cmp(b),
             (Value::Float(a), Value::Int(b)) => a.partial_cmp(&(*b as f64)),
             (Value::Float(a), Value::UInt(b)) => a.partial_cmp(&(*b as f64)),
-            (a, b) => panic!("unable to compare {:?} with {:?}", a, b),
+            (a, b) =>
+            // Compare type ids if types are different.
+            {
+                a.type_of().type_id().partial_cmp(&b.type_of().type_id())
+            }
```
Comment (clarkmcc) [inline interpreter/src/objects.rs]: This would result in a comparison scheme that doesn't follow the [CEL-spec](https://github.com/google/cel-spec/blob/master/doc/langdef.md#ordering) but if we return `None` here, then the interpreter will return an error indicating that the values cannot be compared.
```suggestion
            (a, b) => None,
```

**Review by clarkmcc — CHANGES_REQUESTED** [review]

**Comment by chirino** [comment]
None it is.

**Review by clarkmcc — APPROVED** [review]
