### PR TITLE
Fix default features, cleanup dependencies & other minor code improvements

### LINKED ISSUE #108: Defaulting to features for a compliant CEL interpreter?
With the fix of #90, some "standard" features of CEL are now disabled by default. While I agree with the reason and think that providing this fine grained control over dependencies et al is real great to have in any crate, I wonder if such functionality now behind a feature flag, should be `default` and be an opt-out rather an opt-in. So that anyone grabbing the crate, gets a "std compatible experience" wrt CEL... more so here, as this would be a "slow killer", i.e. only becoming visible at runtime when actually executing some otherwise perfectly fine `Expression`. wdyt? cc/ @Caellian

<details>

i.e.
```diff
diff --git a/interpreter/Cargo.toml b/interpreter/Cargo.toml
index fa70cce..c9fb30e 100644
--- a/interpreter/Cargo.toml
+++ b/interpreter/Cargo.toml
@@ -28,6 +28,7 @@ name = "runtime"
 harness = false
 
 [features]
+default = ["regex", "chrono"]
 json = ["dep:base64", "dep:serde_json"]
 regex = ["dep:regex"]
 chrono = ["dep:chrono"]
```

</details>

### PR DESCRIPTION
**Pull request by Caellian**
- Enabled default features specified in the spec (closes #108).
- Removed patch versions from crates with stable minors.
- ~~Removed `serde` as hard dependency.~~
  - ~~Added support for number casting without serde.~~
- Cleaned up imports.

### CODE REVIEW

File: interpreter/src/testing.rs [hunk 1]
```diff
@@ -1,9 +0,0 @@
-use crate::context::Context;
-use crate::objects::ResolveResult;
-use crate::Program;
-
-/// Tests the provided script and returns the result. An optional context can be provided.
-pub(crate) fn test_script(script: &str, ctx: Option<Context>) -> ResolveResult {
-    let program = Program::compile(script).unwrap();
-    program.execute(&ctx.unwrap_or_default())
-}
```
Comment (Caellian) [inline interpreter/src/testing.rs:9]: Moved this into `lib.rs` `tests` module so it doesn't live in a separate file.

Difference is `use crate::tests` instead of `use crate::testing` and there's less visual noise.

File: interpreter/src/objects.rs [hunk 2]
```diff
@@ -351,16 +358,17 @@ impl From<&Key> for Key {
...
+            Value::Bytes(Arc::new(unsafe {
+                // SAFETY: Checked Vec<T> is Vec<u8>, so they're the same type,
+                // just the compiler can't tell without specialization.
+                std::mem::transmute::<Vec<T>, Vec<u8>>(v)
+            }))
+        } else {
+            Value::List(v.into_iter().map(|v| v.into()).collect::<Vec<_>>().into())
+        }
     }
 }
```
Comment (Caellian) [inline interpreter/src/objects.rs]: Basically merged `From<Vec<T>>` and `From<Vec<u8>>`, this was required to implement `From<u8>` for `Value`.

The if check should effectively be `if const == const` once `T` is resolved, so the compiler will optimize it away.

The only regression here is that now `T: 'static` but I can't think of a case where a Vec of non-static types would be used, so I think this is good enough for now because Value can't hold non-static types at the moment anyway.

File: interpreter/src/magic.rs [hunk 3]
```diff
@@ -7,8 +7,15 @@ use std::marker::PhantomData;
...
+    i8 as i64 => Value::Int,
+    i16 as i64 => Value::Int,
+    i32 as i64 => Value::Int,
     i64 => Value::Int,
+    u8 as u64 => Value::UInt,
+    u16 as u64 => Value::UInt,
+    u32 as u64 => Value::UInt,
     u64 => Value::UInt,
+    f32 as f64 => Value::Float,
     f64 => Value::Float,
```
Comment (Caellian) [inline interpreter/src/magic.rs]: Because `From<number> for Value` is now implemented for all basic numbers.

File: interpreter/src/objects.rs [hunk 4]
```diff
@@ -143,19 +141,28 @@ pub trait TryIntoValue {
...
+#[cfg(not(feature = "serde"))]
+impl<T: Into<Value>> TryIntoValue for T {
+    type Error = Infallible;
+
+    fn try_into_value(self) -> Result<Value, Self::Error> {
+        Ok(self.into())
+    }
+}
```
Comment (Caellian) [inline interpreter/src/objects.rs]: Which was required to implement `TryIntoValue for T: Into<Value>` when serde is disabled.

Aaandd.. that was required because disabling serde broke examples which used simple numbers.

File: interpreter/src/macros.rs [hunk 5]
```diff
@@ -1,12 +1,25 @@
...
+                                target_ty: std::any::type_name::<$target_type>(),
+                            })
+                        } else if <$target_type>::MIN as $cast > *v {
+                            return Err(ExecutionError::CastOverflow {
+                                value: *v as f64,
+                                source_ty: std::any::type_name::<$cast>(),
+                                target_ty: std::any::type_name::<$target_type>(),
+                            })
+                        })?
+                        Ok(v.clone() $(as $cast as $target_type)?)
```
Comment (Caellian) [inline interpreter/src/macros.rs]: This change allows conversion without indirection over `serde` which means that serde can be fully disabled now and the crate will still work with all basic number types.

Double casting in `$(as $cast as $target_type)?` is needed so macro_rules can figure out the cast should be only added when `as $cast` part is specified.

**Review by Caellian — COMMENTED** [review]
Explanation of changes to behavior.

File: interpreter/src/objects.rs (hunk 2 above)
Comment (alexsnaps) [reply interpreter/src/objects.rs]: The life time is on instances of `T`s not the type `T`.
So this, which was perfectly fine before:

```rust
let string = "a".to_string();
let vec = vec![string.as_str()];
let v: Value = vec.into();
```

would not compile anymore:

```
974 |         let string = "a".to_string();
    |             ------ binding `string` declared here
975 |         let vec = vec![string.as_str()];
    |                   -----^^^^^^----------
    |                   |    |
    |                   |    borrowed value does not live long enough
    |                   cast requires that `string` is borrowed for `'static`
...
978 |     }
    |     - `string` dropped here while still borrowed
```

Comment (Caellian) [reply interpreter/src/objects.rs]: It's on type `T`, so it requires that `&str` is `&'static str` because a value can't outlive its type.

But you're right, I added a test for it. I'll revert these changes and move them to a separate PR.

File: interpreter/src/objects.rs [hunk 6]
```diff
@@ -968,4 +968,20 @@ mod tests {
...
+
+        let vec = vec![test.as_str()];
+        let indirect: Value = vec.into();
+        assert_eq!(
+            indirect,
+            Value::List(Arc::new(vec![Value::String(Arc::new(String::from(
+                "example"
+            )))]))
+        );
+    }
```
Comment (Caellian) [inline interpreter/src/objects.rs:974]: As @alexsnaps pointed out, this doesn't work, so I'm drafting this PR until I fix it.

**Comment by Caellian** [comment]
Ok, serde was removed and moved into #109.

**Review by clarkmcc — APPROVED** [review]
