### PR TITLE
Err resilient `OR` & `AND` operators

### LINKED ISSUE #274: Errors in logical operators need to be ignored
Here is a sample test case (which is essentially a port of [CEL-Go lab exercise](https://codelabs.developers.google.com/codelabs/cel-go#6) - specifically the "Run the code with the empty claim set" section):

```rust
use cel::{Context, Program};
use serde::Serialize;

type Group = String;

#[derive(Serialize)]
struct Claims {
    group: Group,
}

#[derive(Serialize)]
struct Auth {
    claims: Option<Claims>,
    principal: String,
}

#[derive(Serialize)]
struct Request {
    auth: Auth,
}

pub fn main() {
    let request = Request {
        auth: Auth {
            principal: "user:me@acme.co".to_string(),
            claims: None,
        },
    };
    let program = Program::compile(
            r#"request.auth.claims.group == 'admin' 
            || request.auth.principal == 'user:me@acme.co'"#
        ).unwrap();
    println!("program: {:?}", program);
    let mut context = Context::default();
    context.add_variable("request", request).unwrap();
    let value = program.execute(&context).unwrap();
    println!("type: {:?}", value.type_of());
    if let cel::Value::Bool(v) = value {
        println!("value: {}", v);
    }
}
```

This should not error. Per the cel-spec on [Logical Operators](https://github.com/google/cel-spec/blob/master/doc/langdef.md#logical-operators):

> In the boolean operators && and ||: if **any of their operands uniquely determines the result** (false for && and true for ||) **the other operand may or may not be evaluated**, **and if that evaluation produces a runtime error, it will be ignored**. This makes those operators commutative (in contrast to traditional boolean short-circuit operators). The rationale for this behavior is to allow the boolean operators to be mapped to indexed queries, and align better with SQL semantics.

The current functionality produces an error with `Err` value set to `NoSuchKey("group")`. Instead it should ignore the error and must return a value set to `true`, with type being a `bool`. It should only throw an error when all of the operands fail to uniquely determine the result.

```bash
> cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.12s
     Running `target/debug/examples/cel-ex1`
program: Program { expression: IdedExpr { id: 12, expr: Call(CallExpr { func_name: "_||_", target: None, args: [IdedExpr { id: 5, expr: Call(CallExpr { func_name: "_==_", target: None, args: [IdedExpr { id: 4, expr: Select(SelectExpr { operand: IdedExpr { id: 3, expr: Select(SelectExpr { operand: IdedExpr { id: 2, expr: Select(SelectExpr { operand: IdedExpr { id: 1, expr: Ident("request") }, field: "auth", test: false }) }, field: "claims", test: false }) }, field: "group", test: false }) }, IdedExpr { id: 6, expr: Literal(String("admin")) }] }) }, IdedExpr { id: 10, expr: Call(CallExpr { func_name: "_==_", target: None, args: [IdedExpr { id: 9, expr: Select(SelectExpr { operand: IdedExpr { id: 8, expr: Select(SelectExpr { operand: IdedExpr { id: 7, expr: Ident("request") }, field: "auth", test: false }) }, field: "principal", test: false }) }, IdedExpr { id: 11, expr: Literal(String("user:me@acme.co")) }] }) }] }) } }

thread 'main' (23846) panicked at examples/cel-ex1.rs:36:43:
called `Result::unwrap()` on an `Err` value: NoSuchKey("group")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This seems to be a bug.

### PR DESCRIPTION
**Pull request by alexsnaps**
fixes #274

### CODE REVIEW

File: cel/src/objects.rs [hunk 1]
```diff
@@ -983,28 +983,40 @@ impl Value {
...
+                            let left = try_bool(Value::resolve_val(&call.args[0], ctx));
+                            return if Ok(true) == left {
+                                Ok(Cow::<dyn Val>::Owned(Box::new(CelBool::from(true))))
                             } else {
-                                let right = Value::resolve_val(&call.args[1], ctx)?;
-                                if right.get_type() == BOOL_TYPE {
-                                    Ok(right)
-                                } else {
-                                    Err(ExecutionError::NoSuchOverload)
+                                let right = Value::resolve_val(&call.args[1], ctx)?
```
Comment (clarkmcc) [inline cel/src/objects.rs:990]: If left side fails, then right side fails (here), it seems like we only ever show the error from the right side, am I reading that correctly?

**Review by clarkmcc — APPROVED** [review]

File: cel/src/objects.rs (hunk 1 above)
Comment (alexsnaps) [reply cel/src/objects.rs:990]: Right, I guess it probably should be lhs one. Is that what you're proposing?
Which [seems to be what the go interpreter does](https://playcel.undistro.io/?content=H4sIAAAAAAAAA6tWSk7NUbJSSsvPV7BTMDRSqKlRSEos0ivOrErV0AQLKekopSSWJHrmFZSWQFRaKaQl5hSnxuQBVVoBVRgDleTmp6QCZUGm1QIAiWAKlFUAAAA%3D)

Comment (clarkmcc) [reply cel/src/objects.rs:990]: Well, showing left if both fail seems more natural to me, but I don't have a strong preference. To your point, for interpreter parity maybe it makes sense to match Go interpreter behavior on this so that error messages match.

Comment (alexsnaps) [reply cel/src/objects.rs:990]: [Fixed](https://github.com/cel-rust/cel-rust/pull/275/changes#diff-2f11c2d14fecf3edd595c9455f71dff7653522fa1b4d4e28ab96e14163f3d89bR1000)
