### PR TITLE
feat: Implement Short-Circuit Evaluation for AND Expressions to Fix Issue #117

### LINKED ISSUE #117: Implement short-circuit evaluation for AND expression
Description:

In the provided example, the AND expression within the compiled program causes an error, which is counterintuitive and violates common programming language conventions.
```rust
let mut context = Context::default();
let data: HashMap<String, String>  = HashMap::new();
context.add_variable_from_value("data", data);
let program = Program::compile("has(data.x) && data.x.startsWith(\"foo\")").unwrap();
```

Expected Behavior:

The AND expression should support short-circuit evaluation. In this case, the data.x.startsWith("foo") part should only be evaluated if has(data.x) returns true. This would prevent unnecessary errors and align with typical programming language behavior.

I have prepared a pull request to address this issue by implementing short-circuit evaluation for AND expressions.

Thank you for your time and effort in maintaining this project.

### PR DESCRIPTION
**Pull request by Masterlvng**
Summary
This pull request implements short-circuit evaluation for AND expressions in the program compiler, enhancing the language's functionality and preventing unnecessary errors.

Related Issue
Fixes #117

### CODE REVIEW

**Comment by Masterlvng** [comment]
Code style issues have been solved.

File: interpreter/src/objects.rs [hunk 1]
```diff
@@ -486,8 +486,12 @@ impl<'a> Value {
             }
             Expression::And(left, right) => {
                 let left = Value::resolve(left, ctx)?;
-                let right = Value::resolve(right, ctx)?;
-                Value::Bool(left.to_bool() && right.to_bool()).into()
+                if !left.to_bool() {
+                    left.into()
```
Comment (clarkmcc) [inline interpreter/src/objects.rs]: Just return false and skip the conversion!

File: interpreter/src/objects.rs [hunk 2]
```diff
@@ -486,8 +486,12 @@ impl<'a> Value {
...
+                } else {
+                    let right = Value::resolve(right, ctx)?;
+                    right.into()
```
Comment (clarkmcc) [inline interpreter/src/objects.rs]: This may not convert into a bool, the into just turns into a Value. We need to explicitly convert to bool so the result of this expression always returns bool.

File: interpreter/src/objects.rs (hunk 1 above)
Comment (Masterlvng) [reply interpreter/src/objects.rs]: got it

**Comment by Masterlvng** [comment]
The linter prompt code issues have been fixed.

**Review by clarkmcc — APPROVED** [review]
Thank you!
